//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1131418_杜語喬_Office_Warfare.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1131418_杜語喬_Office_Warfare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Boss_7 {
            get {
                object obj = ResourceManager.GetObject("Blue_Boss_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Blue_GM_6 {
            get {
                object obj = ResourceManager.GetObject("Blue_GM_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Intern_1 {
            get {
                object obj = ResourceManager.GetObject("Blue_Intern_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Junior_2 {
            get {
                object obj = ResourceManager.GetObject("Blue_Junior_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Leader_4 {
            get {
                object obj = ResourceManager.GetObject("Blue_Leader_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Manager_5 {
            get {
                object obj = ResourceManager.GetObject("Blue_Manager_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Senior_3 {
            get {
                object obj = ResourceManager.GetObject("Blue_Senior_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Red_Boss_7 {
            get {
                object obj = ResourceManager.GetObject("Red_Boss_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Red_GM_6 {
            get {
                object obj = ResourceManager.GetObject("Red_GM_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Red_Intern_1 {
            get {
                object obj = ResourceManager.GetObject("Red_Intern_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Red_Junior_2 {
            get {
                object obj = ResourceManager.GetObject("Red_Junior_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Red_Leader_4 {
            get {
                object obj = ResourceManager.GetObject("Red_Leader_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Red_Manager_5 {
            get {
                object obj = ResourceManager.GetObject("Red_Manager_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Red_Senior_3 {
            get {
                object obj = ResourceManager.GetObject("Red_Senior_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Sys_GameStart {
            get {
                return ResourceManager.GetStream("Sys_GameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Sys_ReadRules {
            get {
                return ResourceManager.GetStream("Sys_ReadRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Sys_ResetGame {
            get {
                return ResourceManager.GetStream("Sys_ResetGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Sys_TurnBlue {
            get {
                return ResourceManager.GetStream("Sys_TurnBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Sys_TurnRed {
            get {
                return ResourceManager.GetStream("Sys_TurnRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Tile_Back {
            get {
                object obj = ResourceManager.GetObject("Tile_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Tile_Empty {
            get {
                object obj = ResourceManager.GetObject("Tile_Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Tile_Selected {
            get {
                object obj = ResourceManager.GetObject("Tile_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Voice_Eat_Counter {
            get {
                return ResourceManager.GetStream("Voice_Eat_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Voice_Eat_Tie {
            get {
                return ResourceManager.GetStream("Voice_Eat_Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Voice_WinBlue {
            get {
                return ResourceManager.GetStream("Voice_WinBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Voice_WinRed {
            get {
                return ResourceManager.GetStream("Voice_WinRed", resourceCulture);
            }
        }
    }
}
